# Generated by Django 4.2.1 on 2023-06-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
        migrations.AddField(
            model_name='graduate',
            name='position',
            field=models.CharField(default='Desing', max_length=250, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
