# Generated by Django 4.2.1 on 2023-06-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('graduates', '0003_alter_graduate_achievement_level_alter_graduate_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='student_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
