# Generated by Django 4.2.1 on 2023-06-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('graduates', '0004_alter_graduate_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
