# Generated by Django 4.2.1 on 2023-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0007_alter_graduate_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='Sin asignar', max_length=250, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sector',
            field=models.CharField(default='Sin asignar', max_length=250, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default='Sin asignar', max_length=250, null=True, verbose_name='Type'),
        ),
    ]
