# Generated by Django 4.2.1 on 2023-06-02 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('previous_user', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Previous User')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Correo')),
                ('previous_email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='Nombres')),
                ('lastname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='Telefono')),
                ('birthday', models.DateField(default=datetime.date(2000, 1, 1), null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1, verbose_name='Género')),
                ('active_user', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('admin_user', models.BooleanField(default=False, verbose_name='Usuario Administrador')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Event Time')),
                ('type', models.CharField(max_length=250, verbose_name='Type')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Event_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(max_length=250, verbose_name='permissions')),
                ('id_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event_User',
            },
        ),
    ]
