# Generated by Django 4.2.1 on 2023-05-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='Nombres')),
                ('lastname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Apellidos')),
                ('phone_Number', models.CharField(blank=True, max_length=7, null=True, verbose_name='Telefono')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('previous_Username', models.CharField(max_length=100, null=True, unique=True, verbose_name='Usuario anterior')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Correo')),
                ('previous_Email', models.CharField(max_length=254, null=True, unique=True, verbose_name='Correo Anterior')),
                ('birthday', models.DateField(null=True, verbose_name='Nacimiento')),
                ('address', models.CharField(max_length=254, null=True, verbose_name='Dirección')),
                ('active_user', models.BooleanField(default=True)),
                ('admin_user', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id_employment', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
                'db_table': 'employment',
            },
        ),
        migrations.CreateModel(
            name='estudent',
            fields=[
                ('id_Estudent', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.PositiveSmallIntegerField()),
                ('career', models.CharField(max_length=50)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudent',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id_teacher', models.IntegerField(primary_key=True, serialize=False)),
                ('Salary', models.FloatField()),
                ('Faculty', models.CharField(max_length=50)),
                ('Id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='graduated',
            fields=[
                ('id_graduated', models.IntegerField(primary_key=True, serialize=False)),
                ('salary_Range', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('email_act', models.CharField(max_length=100)),
                ('previous_email', models.CharField(max_length=100)),
                ('level_Reached', models.CharField(max_length=100)),
                ('work_experience', models.PositiveSmallIntegerField()),
                ('cv', models.BinaryField()),
                ('id_Estudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.estudent')),
                ('id_employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employment')),
            ],
            options={
                'verbose_name': 'Egresado',
                'verbose_name_plural': 'Egresados',
                'db_table': 'graduated',
            },
        ),
        migrations.CreateModel(
            name='administrative',
            fields=[
                ('id_administrative', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('position', models.CharField(max_length=50)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrative',
            },
        ),
    ]
