# Generated by Django 4.1.5 on 2023-05-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Minutes',
        ),
    ]
