# Generated by Django 4.2.1 on 2023-05-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='evaluation_history',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='administrative_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='subject_enrollment',
            name='enrollment_id',
        ),
        migrations.RemoveField(
            model_name='subject_enrollment',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='teacher_subject',
            name='teacher_id',
        ),
        migrations.DeleteModel(
            name='Administrative',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Evaluation_History',
        ),
        migrations.DeleteModel(
            name='Graduate',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student_Subject',
        ),
        migrations.DeleteModel(
            name='Subject_Enrollment',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Teacher_Subject',
        ),
    ]
