# Generated by Django 4.1.5 on 2023-06-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_init',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_finish',
            field=models.TimeField(null=True, verbose_name='Event Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_init',
            field=models.TimeField(null=True, verbose_name='Event Time'),
        ),
    ]
