# Generated by Django 4.2.1 on 2023-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_enrollment_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user_general',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
