# Generated by Django 4.2.1 on 2023-06-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_init',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_finish',
            field=models.TimeField(null=True, verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_init',
            field=models.TimeField(null=True, verbose_name='Hora Inicio'),
        ),
    ]
