# Generated by Django 4.2.1 on 2023-05-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_event_status_alter_user_general_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_general',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
