# Generated by Django 4.2.1 on 2023-05-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_general_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_general',
            name='gender',
            field=models.CharField(default='Femenino', max_length=20, verbose_name='Gender'),
        ),
    ]
