# Generated by Django 4.1.5 on 2023-06-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_event_date_finish_alter_event_date_init_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True, null=True, verbose_name='Status'),
        ),
    ]
