# Generated by Django 4.2.1 on 2023-06-04 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('type', models.CharField(default='Temprana', max_length=250, verbose_name='Type')),
            ],
            options={
                'db_table': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('category', models.CharField(max_length=250, verbose_name='Category')),
                ('required', models.BooleanField(verbose_name='Required')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('schedule', models.CharField(max_length=250, verbose_name='Schedule')),
                ('classroom', models.CharField(max_length=250, verbose_name='Classroom')),
                ('status', models.BooleanField(default='Active', max_length=250, verbose_name='Status')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('faculty', models.CharField(max_length=250, verbose_name='Faculty')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Preg_Ev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.evaluation')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
            ],
            options={
                'db_table': 'Preg_Ev',
            },
        ),
        migrations.CreateModel(
            name='Evaluation_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=250, verbose_name='Semester')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Score')),
                ('type', models.CharField(max_length=250, verbose_name='Type')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'Evaluation_History',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
