# Generated by Django 4.2.1 on 2023-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='teacher_subject',
            name='status',
            field=models.BooleanField(default='Active', max_length=250, verbose_name='Status'),
        ),
    ]
