<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-01 01:36

from django.conf import settings
=======
# Generated by Django 4.2.1 on 2023-05-26 22:55

>>>>>>> 944f203429d9e85b419c11df60451f28341062dc
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('user', '0002_remove_enrollment_student_id_and_more'),
>>>>>>> 944f203429d9e85b419c11df60451f28341062dc
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=7, verbose_name='Cost')),
                ('academic_period', models.CharField(max_length=10, verbose_name='Academic Period')),
                ('credit_count', models.PositiveSmallIntegerField(verbose_name='Credit Count')),
<<<<<<< HEAD
                ('status', models.BooleanField(default=True, max_length=10, verbose_name='Status')),
=======
                ('status', models.CharField(default='Active', max_length=10, verbose_name='Status')),
>>>>>>> 944f203429d9e85b419c11df60451f28341062dc
            ],
            options={
                'db_table': 'Enrollment',
            },
        ),
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('shift', models.CharField(max_length=250, verbose_name='Shift')),
                ('schedule', models.CharField(max_length=250, verbose_name='Schedule')),
            ],
            options={
                'db_table': 'Student_Subject',
            },
        ),
        migrations.CreateModel(
            name='Subject_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.enrollment')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_subject')),
            ],
            options={
                'db_table': 'Subject_Enrollment',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semester')),
                ('major', models.CharField(max_length=250, verbose_name='Major')),
<<<<<<< HEAD
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user_general')),
>>>>>>> 944f203429d9e85b419c11df60451f28341062dc
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
