# Generated by Django 4.2.1 on 2023-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=True, max_length=10, verbose_name='Status'),
        ),
    ]
