# Generated by Django 4.2.1 on 2023-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
