# Generated by Django 4.1.5 on 2023-05-31 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'db_table': 'Commitee',
            },
        ),
        migrations.CreateModel(
            name='ActType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.committee')),
            ],
            options={
                'db_table': 'ActTypes',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('current_date', models.DateField(verbose_name='Current Date')),
                ('modification_date', models.DateField(verbose_name='Modification Date')),
                ('document', models.FileField(upload_to='filesAct/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Document')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('administrative_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.administrative')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.committee')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.acttype', verbose_name='Type')),
            ],
            options={
                'db_table': 'Acts',
            },
        ),
    ]
