# Generated by Django 4.2.1 on 2023-06-01 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'Comite',
            },
        ),
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Administrative',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('type', models.CharField(max_length=250, verbose_name='Tipo')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('date_actual', models.DateField(verbose_name='Fecha Actual')),
                ('date_modify', models.DateField(verbose_name='Fecha Modificacion')),
                ('document', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Document')),
                ('state', models.BooleanField(default=True)),
                ('id_administrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.administrative')),
                ('id_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.comite')),
            ],
            options={
                'db_table': 'Act',
            },
        ),
    ]
