# Generated by Django 4.2.1 on 2023-05-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='act',
            table='Act',
        ),
    ]
