# Generated by Django 4.1.5 on 2023-06-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='current_date',
            field=models.DateField(auto_now_add=True, verbose_name='Current Date'),
        ),
        migrations.AlterField(
            model_name='act',
            name='modification_date',
            field=models.DateField(auto_now_add=True, verbose_name='Modification Date'),
        ),
    ]
