# Generated by Django 4.2.1 on 2023-06-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comite',
            table='Comite',
        ),
    ]
