# Generated by Django 4.2.1 on 2023-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_act_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
