# Generated by Django 4.1.5 on 2023-06-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_act_current_date_alter_act_modification_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committee',
            table='Committee',
        ),
    ]
