# Generated by Django 4.1.5 on 2023-06-01 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_committee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='document',
            field=models.FileField(null=True, upload_to='filesAct/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Document'),
        ),
    ]
